export const GET_All_CITIES_REQUEST = 'GET_All_CITIES_REQUEST'
export const GET_All_CITIES_RECEIVE = 'GET_All_CITIES_RECEIVE'

export const GET_All_AIRCRAFTS_REQUEST = 'GET_All_AIRCRAFTS_REQUEST'
export const GET_All_AIRCRAFTS_RECEIVE = 'GET_All_AIRCRAFTS_RECEIVE'

export const GET_All_AIRLINES_REQUEST = 'GET_All_AIRLINES_REQUEST'
export const GET_All_AIRLINES_RECEIVE = 'GET_All_AIRLINES_RECEIVE'

export const GET_All_SEARCH_TICKET_REQUEST = 'GET_All_SEARCH_TICKET_REQUEST'
export const GET_All_SEARCH_TICKET_RECEIVE = 'GET_All_SEARCH_TICKET_RECEIVE'